import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ShoppingCart } from "@/components/common/shopping-cart/ShoppingCart";
import { HeaderProviderWrapper } from "@/components/common/header/HeaderProviderWrapper";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Samurai Express",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderProviderWrapper>
          <ShoppingCart>{children}</ShoppingCart>
        </HeaderProviderWrapper>
      </body>
    </html>
  );
}
